import { PrismaClient } from "@prisma/client";
import * as dotenv from "dotenv";

dotenv.config();

const prisma = new PrismaClient();

async function main() {
  console.log("Start seeding...");

  // Create categories
  const granosCategory = await prisma.category.upsert({
    where: { slug: "granos" },
    update: {},
    create: {
      name: "Granos",
      slug: "granos",
    },
  });

  const pasteleriaCategory = await prisma.category.upsert({
    where: { slug: "pasteleria" },
    update: {},
    create: {
      name: "Pasteleria",
      slug: "pasteleria",
    },
  });

  const merchCategory = await prisma.category.upsert({
    where: { slug: "merch" },
    update: {},
    create: {
      name: "Merch",
      slug: "merch",
    },
  });

  // Create products - Imágenes de Unsplash
  const products = [
    // GRANOS - Cafés
    {
      name: "Patagonia Resiliente",
      description: "Nuestra mezcla de casa. Un café balanceado que combina la mejor selección de granos de América Latina y África. Notas de chocolate amargo, nuez y un toque de frutos rojos. Perfecto para cualquier método de preparación.",
      price: 12000,
      image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80",
      categoryId: granosCategory.id,
      grindOptions: ["Whole Bean", "Espresso", "French Press", "Filter"],
      tastingNotes: "Chocolate, Nuez, Frutos rojos",
      origin: "Blend",
      altitude: "1200-1800 msnm",
      process: "Lavado",
      body: 3,
      acidity: 2,
      stock: 50,
    },
    {
      name: "Cactus High",
      description: "Originario de las tierras altas de Colombia. Este café de altura excepcional ofrece una acidez brillante con notas de cítricos y caramelo. Un reflejo perfecto de la resiliencia de la Patagonia.",
      price: 15000,
      image: "https://images.unsplash.com/photo-1610632380989-680fe40816c6?w=800&q=80",
      categoryId: granosCategory.id,
      grindOptions: ["Whole Bean", "Espresso", "French Press", "Filter"],
      tastingNotes: "Cítricos, Caramelo, Floral",
      origin: "Huila, Colombia",
      altitude: "1800-2100 msnm",
      process: "Lavado",
      body: 2,
      acidity: 4,
      stock: 35,
    },
    {
      name: "Glacial Blend",
      description: "Una mezcla oscura y audaz inspirada en los glaciares del sur. Notas intensas de chocolate oscuro, ahumado y especias. Ideal para aquellos que buscan un café con carácter y cuerpo.",
      price: 13000,
      image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80",
      categoryId: granosCategory.id,
      grindOptions: ["Whole Bean", "Espresso", "French Press", "Filter"],
      tastingNotes: "Chocolate oscuro, Ahumado, Especias",
      origin: "Blend",
      altitude: "1000-1500 msnm",
      process: "Natural",
      body: 5,
      acidity: 1,
      stock: 40,
    },
    {
      name: "Torres del Paine Single Origin",
      description: "Café de origen único de Etiopía con notas distintivas de frutos oscuros, bergamota y miel. Una experiencia sensorial única como las Torres del Paine.",
      price: 18000,
      image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&q=80",
      categoryId: granosCategory.id,
      grindOptions: ["Whole Bean", "Espresso", "French Press", "Filter"],
      tastingNotes: "Frutos oscuros, Bergamota, Miel",
      origin: "Yirgacheffe, Etiopía",
      altitude: "1900-2200 msnm",
      process: "Lavado",
      body: 2,
      acidity: 5,
      stock: 25,
    },
    {
      name: "Fitz Roy Espresso",
      description: "Blend especialmente diseñado para espresso. Intenso, con cuerpo completo y crema persistente. Notas de cacao, panela y nuez.",
      price: 14000,
      image: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=800&q=80",
      categoryId: granosCategory.id,
      grindOptions: ["Whole Bean", "Espresso"],
      tastingNotes: "Cacao, Panela, Nuez",
      origin: "Blend Brasil - Colombia",
      altitude: "1100-1700 msnm",
      process: "Lavado",
      body: 4,
      acidity: 2,
      stock: 45,
    },
    {
      name: "Bagual Morning",
      description: "Café perfecto para comenzar la mañana. Suave, balanceado y fácil de beber. Notas de galleta, vainilla y leche tostada.",
      price: 11000,
      image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
      categoryId: granosCategory.id,
      grindOptions: ["Whole Bean", "Espresso", "French Press", "Filter"],
      tastingNotes: "Galleta, Vainilla, Leche tostada",
      origin: "Blend",
      altitude: "1200-1600 msnm",
      process: "Lavado",
      body: 3,
      acidity: 3,
      stock: 60,
    },
    {
      name: "Selknam Decaf",
      description: "Café descafeinado de montaña sin perder el sabor. Proceso Swiss Water que mantiene todas las características del grano original.",
      price: 14500,
      image: "https://images.unsplash.com/photo-1559525839-b184a4d698c7?w=800&q=80",
      categoryId: granosCategory.id,
      grindOptions: ["Whole Bean", "Espresso", "French Press", "Filter"],
      tastingNotes: "Chocolate suave, Caramelo, Frutos secos",
      origin: "Colombia",
      altitude: "1600-1900 msnm",
      process: "Swiss Water",
      body: 3,
      acidity: 2,
      stock: 30,
    },
    {
      name: "Kawésqar Reserve",
      description: "Edición limitada de micro-lote. Café excepcional con notas complejas de tropical, jasmine y miel de ulmo. Solo 50kg disponibles.",
      price: 22000,
      image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80",
      categoryId: granosCategory.id,
      grindOptions: ["Whole Bean", "Filter"],
      tastingNotes: "Tropical, Jasmine, Miel de ulmo",
      origin: "Nariño, Colombia",
      altitude: "2100-2300 msnm",
      process: "Lavado - Fermentación extendida",
      body: 2,
      acidity: 5,
      stock: 8,
    },

    // PASTELERÍA - Pasteles
    {
      name: "Torta de Tres Leches Patagonia",
      description: "Nuestra versión patagónica del clásico. Tres tipos de leche, bizcocho húmedo y merengue italiano. Esponjosa y decadente.",
      price: 8500,
      image: "https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Dulce, Vainilla, Leche",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 12,
    },
    {
      name: "Cheesecake Calafate",
      description: "Cheesecake de Nueva York con coulis de calafate silvestre. La acidez única de esta baya patagónica complementa perfectamente el cremoso queso crema.",
      price: 7500,
      image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Cremoso, Ácido, Calafate",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 15,
    },
    {
      name: "Brownie Glacial",
      description: "Brownie denso y chocolateado con trozos de chocolate amargo y nueces. Servido caliente con helado de vainilla.",
      price: 6500,
      image: "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Chocolate, Nueces, Caramelo",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 18,
    },
    {
      name: "Croissant de Mantequilla",
      description: "Croissant francés clásico hecho con mantequilla premium. Capas crujientes por fuera, tierno y aireado por dentro. Horneado cada mañana.",
      price: 3500,
      image: "https://images.unsplash.com/photo-1555507036-ab1f40388085?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Mantequilla, Crujiente, Hojaldrado",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 25,
    },
    {
      name: "Muffin de Arándanos",
      description: "Muffin esponjoso con arándanos frescos y streusel crujiente. Perfecto para acompañar tu café de la mañana.",
      price: 4000,
      image: "https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Arándanos, Vainilla, Cítrico",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 20,
    },
    {
      name: "Alfajor Cactus",
      description: "Dos suaves galletas de maicena rellenas con dulce de leche y bañadas en chocolate. Nuestra versión con forma de cactus.",
      price: 3000,
      image: "https://images.unsplash.com/photo-1621893027164-7320cf14a07b?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Dulce de leche, Chocolate, Vainilla",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 30,
    },
    {
      name: "Torta Selknam",
      description: "Torta de chocolate intenso con ganache y ganache de calafate. Decorada con motivos inspirados en la cultura Selk'nam.",
      price: 9000,
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Chocolate, Calafate, Intenso",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 8,
    },
    {
      name: "Scones de Queso",
      description: "Scones salados con queso chubut y hierbas frescas. Perfectos con un café por la tarde.",
      price: 4500,
      image: "https://images.unsplash.com/photo-1619221882220-4479aff00bf0?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Queso, Hierbas, Salado",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 16,
    },
    {
      name: "Macarons Patagonia",
      description: "Caja de 5 macarons con sabores de la región: calafate, murta, chocolates, vainilla y frambuesa. Almendras finas y ganache francesa.",
      price: 8000,
      image: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Frutal, Almendra, Dulce",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 14,
    },
    {
      name: "Tarta de Limón",
      description: "Tarta de limón con curd brillante y merengue italiano tostado. El equilibrio perfecto entre ácido y dulce.",
      price: 7000,
      image: "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Limón, Ácido, Merengue",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 10,
    },
    {
      name: "Cookie Gigante",
      description: "Cookie masiva con trozos de chocolate belga y nueces. Borde crujiente, centro suave y derretido.",
      price: 4500,
      image: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80",
      categoryId: pasteleriaCategory.id,
      grindOptions: [],
      tastingNotes: "Chocolate, Nueces, Vainilla",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 22,
    },

    // MERCH - Merchandising
    {
      name: "Tote Bag Patagonia",
      description: "Bolsa de tela resistente con diseño exclusivo de Adventure Cactus Coffee. Perfecta para tu laptop o compra diaria.",
      price: 12000,
      image: "https://images.unsplash.com/photo-1597484661643-2f5fef26aa4b?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 40,
    },
    {
      name: "T-Shirt Logo - Negro",
      description: "Camiseta de algodón premium con logo bordado. Fit moderno, cómoda y duradera. Disponible en tallas S a XL.",
      price: 18000,
      image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 25,
    },
    {
      name: "T-Shirt Mountains - Beige",
      description: "Camiseta con diseño de montañas y slogan 'Café al Fin del Mundo'. Algodón orgánico certificado.",
      price: 19000,
      image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 20,
    },
    {
      name: "Hoodie Adventure",
      description: "Polerón oversize de fleece premium. Logo pequeño en pecho y diseño grande en espalda. Perfecto para aventuras outdoor.",
      price: 35000,
      image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 15,
    },
    {
      name: "Taza Cerámica Resiliente",
      description: "Taza de cerámica artesanal con textura de cactus. 350ml, perfecta para tu café favorito. Cada pieza es única.",
      price: 9500,
      image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 30,
    },
    {
      name: "Travel Mug Adventure",
      description: "Taza térmica de acero inoxidable con cierre hermético. Mantiene tu café caliente por 6 horas. Diseño compacto.",
      price: 22000,
      image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 18,
    },
    {
      name: "Gorra Patagonia",
      description: "Gorra snapback con logo bordado en 3D. Ajustable, cómoda y con protección UV para tus aventuras.",
      price: 15000,
      image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 22,
    },
    {
      name: "Sticker Pack",
      description: "Pack de 10 stickers vinilo de alta calidad. Diseños exclusivos de Adventure Cactus Coffee. Ideales para laptop, botella o mochila.",
      price: 5000,
      image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 50,
    },
    {
      name: "Poster Torres del Paine",
      description: "Impresión artística de las Torres del Paine con elementos de café. Papel cotton de 200gr, tamaño 50x70cm.",
      price: 16000,
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 12,
    },
    {
      name: "Mochila Daypack",
      description: "Mochila técnica compacta para day hikes. Compartimento hidratante, bolsos organizadores y diseño ergonómico.",
      price: 45000,
      image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      categoryId: merchCategory.id,
      grindOptions: [],
      tastingNotes: "",
      origin: null,
      altitude: null,
      process: null,
      body: 0,
      acidity: 0,
      stock: 10,
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { id: product.name.toLowerCase().replace(/\s+/g, "-") },
      update: {
        name: product.name,
        description: product.description,
        price: product.price,
        image: product.image,
        grindOptions: product.grindOptions,
        tastingNotes: product.tastingNotes,
        origin: product.origin,
        altitude: product.altitude,
        process: product.process,
        body: product.body,
        acidity: product.acidity,
        stock: product.stock,
      },
      create: {
        ...product,
        id: product.name.toLowerCase().replace(/\s+/g, "-"),
      },
    });
  }

  console.log(`Seeding finished. Updated ${products.length} products.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
